---

- name: 'Ansible Pull'
  hosts: localhost
  connection: local
  #remote_user: root
  become_user: root
  become: True
  
  vars:
    # Become Pass
    ansible_become_pass: '{{ dev2771_become_pass }}'

    # schedule is fed directly to cron
    schedule: '*/1 * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    #repo_url: git://github.com/sfromm/ansible-playbooks.git
    repo_url: https://github.com/ichibsah/ansible-semaphore.git

  roles:
    - ansbl_pull
