---

- name: 'QIT Automation 1.0'
  hosts: all
  #connection: local
  #remote_user: adminqit
  #remote_user: adminqit
  #ansible_user: adminqit #ERROR! 'ansible_user' is not a valid attribute for a Play
  #become: true
  #gathering: smart #ERROR! 'gathering' is not a valid attribute for a Play
  gather_facts: True
  ignore_errors: True
  ignore_unreachable: true
  #become_method: runas 
  #become_user: adminqit
  

  vars:
    #+ansible_remote_user: adminqit #ERROR! 'ansible_remote_user' is not a valid attribute for a Play
    #+ansible_ssh_user: adminqit #ERROR! 'ansible_ssh_user' is not a valid attribute for a Play
    #ansible_shell_type: powershell #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    ansible_shell_type: cmd #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    #shell_type: powershell #ERROR! 'shell_type' is not a valid attribute for a Play
    #remote_tmp: C:\Tmp
    #ansible_remote_tmp: c\temp
    #remote_tmp: c\temp
    #ansible_ssh_password: adminqit
    #ansible_become_pass: '{{ jenkins_become_pass }}'
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      # ansible_user: ansible
      # ansible_password: "{{ password }}"
      # ansible_connection: winrm
      # ansible_winrm_transport: ntlm
      # ansible_winrm_server_cert_validation: ignore
    logpath: C:\ansible-log
    filename: "{{ lookup('pipe', 'date +%Y%m%d') }}.log"

# Note
# ansible-galaxy collection install community.windows --force
# use this in powershell to get the current code
# wmic os get locale
# Get-Culture
# Get-UICulture

  tasks:
  - name: Job-id 1100 | Create Ansible logs directory structure
    ansible.windows.win_file:
      path: "{{logpath}}"
      state: directory
      
- name: NTP test
  hosts: ism
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "Set ntp"
    inspur.sm.edit_ntp:
      auto_date: "enable"
      server2: "time.nist.gov"
      provider: "{{ ism }}"

  - name: "Set ntp"
    inspur.sm.edit_ntp:
      auto_date: "disable"
      ntp_time: "20200609083600"
      provider: "{{ ism }}"

  - name: "set ntp"
    inspur.sm.edit_ntp:
      time_zone: 8
      provider: "{{ ism }}"