---

- name: 'QIT Automation 1.0'
  hosts: all
  #connection: local
  #remote_user: adminqit
  #remote_user: adminqit
  #ansible_user: adminqit #ERROR! 'ansible_user' is not a valid attribute for a Play
  #become: true
  #gathering: smart #ERROR! 'gathering' is not a valid attribute for a Play
  gather_facts: True
  ignore_errors: True
  ignore_unreachable: true
  #become_method: runas 
  #become_user: adminqit
  

  vars:
    ansible_remote_user: adminqit #ERROR! 'ansible_remote_user' is not a valid attribute for a Play
    ansible_ssh_user: adminqit #ERROR! 'ansible_ssh_user' is not a valid attribute for a Play
    #ansible_shell_type: powershell #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    ansible_shell_type: cmd #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    #shell_type: powershell #ERROR! 'shell_type' is not a valid attribute for a Play
    #remote_tmp: C:\Tmp
    #ansible_remote_tmp: c\temp
    #remote_tmp: c\temp
    #ansible_ssh_password: adminqit
    #ansible_become_pass: '{{ jenkins_become_pass }}'
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      # ansible_user: ansible
      # ansible_password: "{{ password }}"
      # ansible_connection: winrm
      # ansible_winrm_transport: ntlm
      # ansible_winrm_server_cert_validation: ignore
    logpath: C:\ansible-log
    filename: "{{ lookup('pipe', 'date +%Y%m%d') }}.log"


  tasks: 
  - name: Job-id 1100 | Create Ansible logs directory structure
    ansible.windows.win_file:
      path: "{{logpath}}"
      state: directory

  - name: Job-id 1101 |Install Notepad++ version 7.8
    win_chocolatey:
      name: notepadplusplus
      version: ‘7.8’
      #log_path: "{{logpath}}\\job-1101-{{filename}}"