---

- name: 'QIT Automation 1.0'
  #hosts: all
  hosts: localhost
  connection: local
  #remote_user: adminqit
  #remote_user: adminqit
  #ansible_user: adminqit #ERROR! 'ansible_user' is not a valid attribute for a Play
  #become: true
  #gathering: smart #ERROR! 'gathering' is not a valid attribute for a Play
  gather_facts: True
  ignore_errors: True
  ignore_unreachable: true
  #become_method: runas 
  #become_user: adminqit
  

  vars:
    #+ansible_remote_user: adminqit #ERROR! 'ansible_remote_user' is not a valid attribute for a Play
    #+ansible_ssh_user: adminqit #ERROR! 'ansible_ssh_user' is not a valid attribute for a Play
    #ansible_shell_type: powershell #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    #####ansible_shell_type: cmd #ERROR! 'ansible_shell_type' is not a valid attribute for a Play
    #shell_type: powershell #ERROR! 'shell_type' is not a valid attribute for a Play
    #remote_tmp: C:\Tmp
    #ansible_remote_tmp: c\temp
    #remote_tmp: c\temp
    #ansible_ssh_password: adminqit
    #ansible_become_pass: '{{ jenkins_become_pass }}'
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      # ansible_user: ansible
      # ansible_password: "{{ password }}"
      # ansible_connection: winrm
      # ansible_winrm_transport: ntlm
      # ansible_winrm_server_cert_validation: ignore
    logpath: C:\ansible-log
    filename: "{{ lookup('pipe', 'date +%Y%m%d') }}.log"

# Note
# https://docs.ansible.com/ansible/latest/collections/community/general/wakeonlan_module.html
# ansible-galaxy collection install community.general

  tasks:
  - name: Send a magic Wake-on-LAN packet port 7
    community.general.wakeonlan:
      #mac: '00:0C:29:55:59:68'
      #mac: '00:0c:29:8b:df:24'
      mac: '00:0c:29:c9:43:93' # 2498
      broadcast: 255.255.255.255 # Default: "255.255.255.255"
      #broadcast: 10.30.0.255
    delegate_to: localhost

  - name: Send a magic Wake-on-LAN packet port 9
    community.general.wakeonlan:
      #mac: 00:0C:29:55:59:68
      #mac: 00:0c:29:8b:df:24 #2271
      mac: 00:0c:29:c9:43:93 # 2498
      port: 9 # Default: 7
    delegate_to: localhost