---
# https://clarusway.com/creating-adding-authorizing-users-and-groups-with-ansible/
# tasks file for users

- name: creating users and groups and ssh connection
  ansible.builtin.user:
    name: "{{item.name}}"
    shell: "{{item.shell}}"
    groups: "{{item.group}}"
    append: "{{item.append}}"
  loop:
    - users

- authorized_key:
    user: "{{item.name}}"
    state: "{{item.state}}"
    key: "{{ lookup('file', './file/{{item.key}}') }}"
  loop:
    - users
