---
# https://clarusway.com/creating-adding-authorizing-users-and-groups-with-ansible/
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
# https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html
# tasks file for users

- name: creating users and groups and ssh connection
  user:
    name: "{{item.name}}"
    update_password: always
    shell: "{{item.shell}}"
    groups: "{{item.groups}}"
    #password: "{{ localhost_become_pass | password_hash('sha512') }}"
    append: "{{item.append}}"
    create_home: True
    state: present
  loop: "{{ users }}"
  when: "{{item.hosts}}" is "all" or "{{item.hosts}}" is "{{ansible_hostname}}"

- authorized_key:
    user: "{{item.name}}"
    state: "{{item.state}}"
    key: "{{ lookup('file', 'files/authorized_key/{{item.key}}') }}"
  loop: "{{ users }}"
  when: "{{item.hosts}}" is "all" or "{{item.hosts}}" is "{{ansible_hostname}}"