---
# https://clarusway.com/creating-adding-authorizing-users-and-groups-with-ansible/
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
# tasks file for users

- name: creating users and groups and ssh connection
  user:
    name: "{{item.name}}"
    update_password: always
    shell: "{{item.shell}}"
    groups: "{{item.groups}}"
    #password: "{{ localhost_become_pass | password_hash('sha512') }}"
    append: "{{item.append}}"
    create_home: True
    state: present
  loop: "{{ users }}"

- authorized_key:
    user: "{{item.name}}"
    state: "{{item.state}}"
    key: "{{ lookup('file', 'files/{{item.key}}') }}"
  loop: "{{ users }}"
